baseURL: 'https://european-dream.eu/'
title: 'European Dream'
languageCode: en
DefaultContentLanguage: en
enableEmoji: true
enableGitInfo: false
enableRobotsTXT: true
canonifyURLs: false
pagination:
  pagerSize: 9
enableInlineShortcodes: true

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

menus:
  main:
    - identifier: why
      name: Why?
      url: /why/
      weight: 10
    - identifier: goals
      name: Our Goals
      url: /goals/
      weight: 20
    - identifier: roadmap
      name: Roadmap
      url: /roadmap/
      weight: 30
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 40
  footer:
    - identifier: why
      name: Why?
      url: /why/
      weight: 10
    - identifier: goals
      name: Our Goals
      url: /goals/
      weight: 20
    - identifier: roadmap
      name: Roadmap
      url: /roadmap/
      weight: 30
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 40
    - identifier: identity
      name: Identity
      url: /identity/
      weight: 50

module:
  hugoVersion:
    extended: true
    min: "0.153.0"

caches:
  assets:
    dir: :cacheDir/assets
    maxAge: "0s" # Disable caching in development
  getcsv:
    dir: :cacheDir/getcsv
    maxAge: 3600s # 1 hour
  getjson:
    dir: :cacheDir/getjson
    maxAge: 3600s # 1 hour
  images:
    dir: :cacheDir/images
    maxAge: 8760h # 1 year
  modules:
    dir: :cacheDir/modules
    maxAge: 8760h # 1 year

imaging:
  quality: 85
  resampleFilter: Lanczos
  anchor: Smart
