baseURL: 'https://european-dream.eu/'
title: 'European Dream'

canonifyURLs: false
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableEmoji: true
enableGitInfo: false
enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 9

caches:
  assets:
    dir: :cacheDir/assets
    maxAge: "0s" # Disable caching in development
  getcsv:
    dir: :cacheDir/getcsv
    maxAge: 3600s # 1 hour
  getjson:
    dir: :cacheDir/getjson
    maxAge: 3600s # 1 hour
  images:
    dir: :cacheDir/images
    maxAge: 8760h # 1 year
  modules:
    dir: :cacheDir/modules
    maxAge: 8760h # 1 year

imaging:
  quality: 85
  resampleFilter: Lanczos
  anchor: Smart

languages:
  en:
    languageCode: en
    languageName: English
    weight: 1
    params:
      description: 'A non-profit initiative dreaming and building a post-transactional world, rooted in the European Union.'
  fr:
    languageCode: fr
    languageName: Français
    weight: 2
    params:
      description: Une initiative à but non lucratif qui rêve et bâtit un monde post-transactionnel, à l'échelle de l'Union européenne.
  de:
    languageCode: de
    languageName: Deutsch
    weight: 3
    params:
      description: Eine gemeinnützige Initiative, die von einer post-transaktionalen Welt träumt und sie aufbaut – verwurzelt in der Europäischen Union.
  es:
    languageCode: es
    languageName: Español
    weight: 4
    params:
      description: Una iniciativa sin ánimo de lucro que sueña y construye un mundo post-transaccional, arraigada en la Unión Europea.
  it:
    languageCode: it
    languageName: Italiano
    weight: 5
    params:
      description: Un'iniziativa senza scopo di lucro che sogna e costruisce un mondo post-transazionale, radicata nell'Unione europea.
  pl:
    languageCode: pl
    languageName: Polski
    weight: 6
    params:
      description: Inicjatywa non-profit, która marzy i buduje świat post-transakcyjny, zakorzeniona w Unii Europejskiej.
  pt:
    languageCode: pt
    languageName: Português
    weight: 7
    params:
      description: Uma iniciativa sem fins lucrativos que sonha e constrói um mundo pós-transacional, enraizada na União Europeia.
  ro:
    languageCode: ro
    languageName: Română
    weight: 8
    params:
      description: O inițiativă non-profit care visează și construiește o lume post-tranzacțională, înrădăcinată în Uniunea Europeană.

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

module:
  hugoVersion:
    extended: true
    min: "0.153.0"

outputs:
  home:
    - html
    - rss
  section:
    - html
  taxonomy: []
  term: []

params:
  utmSource: european_dream

security:
  funcs:
    getenv:
      - '^HUGO_'
      - 'UNSPLASH_API_ACCESS_KEY'
