baseURL: 'https://european-dream.eu/'
title: 'European Dream'

canonifyURLs: false
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableEmoji: true
enableGitInfo: false
enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 9

caches:
  assets:
    dir: :cacheDir/assets
    maxAge: "0s" # Disable caching in development
  getcsv:
    dir: :cacheDir/getcsv
    maxAge: 3600s # 1 hour
  getjson:
    dir: :cacheDir/getjson
    maxAge: 3600s # 1 hour
  images:
    dir: :cacheDir/images
    maxAge: 8760h # 1 year
  modules:
    dir: :cacheDir/modules
    maxAge: 8760h # 1 year

imaging:
  quality: 85
  resampleFilter: Lanczos
  anchor: Smart

languages:
  en:
    languageCode: en
    languageName: English
    weight: 1
    params:
      description: 'A non-profit initiative dreaming and building a post-transactional world, rooted in the European Union.'
  fr:
    languageCode: fr
    languageName: Français
    weight: 2
    params:
      description: Une initiative à but non lucratif qui rêve et bâtit un monde post-transactionnel, à l'échelle de l'Union européenne.

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

module:
  hugoVersion:
    extended: true
    min: "0.153.0"

params:
  utmSource: european_dream

security:
  funcs:
    getenv:
      - '^HUGO_'
      - 'UNSPLASH_API_ACCESS_KEY'
