main:
  - name: A Call To Dream
    pageRef: /a-call-to-dream/
    weight: 10
  - name: Our Goals
    pageRef: /our-goals/
    weight: 20
  - name: Roadmap
    pageRef: /roadmap/
    weight: 30
  - name: Contact
    pageRef: /contact/
    weight: 40
footer:
  - name: Identity
    pageRef: /identity/
    weight: 10
  - name: Website Elements
    pageRef: /website-elements/
    weight: 20
  - name: Why?
    pageRef: /why/
    weight: 30
