main:
  - name: Una Llamada A Soñar
    pageRef: /a-call-to-dream/
    weight: 10
  - name: Nuestros Objetivos
    pageRef: /our-goals/
    weight: 20
  - name: Hoja de Ruta
    pageRef: /roadmap/
    weight: 30
  - name: Únase a Nosotros
    pageRef: /join-us/
    weight: 40
  - name: Contacto
    pageRef: /contact/
    weight: 50
footer:
  - name: Identidad
    pageRef: /identity/
    weight: 10
  - name: Elementos del Sitio Web
    pageRef: /website-elements/
    weight: 20
