main:
  - name: Um apelo a sonhar
    pageRef: /a-call-to-dream/
    weight: 10
  - name: Os nossos objetivos
    pageRef: /our-goals/
    weight: 20
  - name: Roteiro
    pageRef: /roadmap/
    weight: 30
  - name: Junte-se a n√≥s
    pageRef: /join-us/
    weight: 40
  - name: Contacto
    pageRef: /contact/
    weight: 50
footer:
  - name: Identidade
    pageRef: /identity/
    weight: 10
  - name: Elementos do site
    pageRef: /website-elements/
    weight: 20
