main:
  - name: Un apel la vis
    pageRef: /a-call-to-dream/
    weight: 10
  - name: Obiectivele noastre
    pageRef: /our-goals/
    weight: 20
  - name: Foaie de parcurs
    pageRef: /roadmap/
    weight: 30
  - name: Alătură-te nouă
    pageRef: /join-us/
    weight: 40
  - name: Contact
    pageRef: /contact/
    weight: 50
footer:
  - name: Identitate
    pageRef: /identity/
    weight: 10
  - name: Elemente ale site-ului
    pageRef: /website-elements/
    weight: 20
