main:
  - name: Ein Aufruf zu träumen
    pageRef: /a-call-to-dream/
    weight: 10
  - name: Unsere Ziele
    pageRef: /our-goals/
    weight: 20
  - name: Fahrplan
    pageRef: /roadmap/
    weight: 30
  - name: Mitmachen
    pageRef: /join-us/
    weight: 40
  - name: Kontakt
    pageRef: /contact/
    weight: 50
footer:
  - name: Identität
    pageRef: /identity/
    weight: 10
  - name: Website-Elemente
    pageRef: /website-elements/
    weight: 20
