main:
  - name: Un invito a sognare
    pageRef: /a-call-to-dream/
    weight: 10
  - name: I nostri obiettivi
    pageRef: /our-goals/
    weight: 20
  - name: Roadmap
    pageRef: /roadmap/
    weight: 30
  - name: Unisciti a noi
    pageRef: /join-us/
    weight: 40
  - name: Contatti
    pageRef: /contact/
    weight: 50
footer:
  - name: Identit√†
    pageRef: /identity/
    weight: 10
  - name: Elementi del sito
    pageRef: /website-elements/
    weight: 20
